version: "3"
services:

  postgres:
    restart: always
    build: ./postgres/
    container_name: postgres
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    expose:
      - "54321"
    environment:
      POSTGRES_DB: db_project
      POSTGRES_USER: project
      POSTGRES_PASSWORD: project

  redis:
    restart: always
    image: redis
    container_name: redis
    expose:
      - "6379"

  python:
    restart: always
    build: ./python/
    container_name: python
    ports:
      - "8000:8000"
    links:
      - postgres:postgres
      - redis:redis
    volumes:
      - ./python/data:/www
    command: circusd /www/circus.ini

  nginx:
    restart: always
    build: ./nginx/
    container_name: nginx
    image: nginx
    privileged: true
    environment:
      NGINX_PORT: 80
      NGINX_HOST: 127.0.0.1
    ports:
      - "80:80"
    volumes:
      - ./nginx/data:/usr/share/nginx/html
      - ./nginx/mysite.template:/etc/nginx/conf.d/mysite.template
      - ./python/data/static:/usr/share/nginx/html/static
      - ./python/data/uploads:/usr/share/nginx/html/uploads
    links:
      - python:python
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

#  flower:
#    restart: always
#    build: ./flower/
#    container_name: flower
#    ports:
#      - "5000:5000"
#    links:
#      - redis:redis
#    command: celery flower --basic_auth=admin:admin --address=0.0.0.0 --port=5000 --broker=redis://redis:6379/10