version: "3.5"
services:
  postgres:
    restart: always
    privileged: true
    build:
      context: ./postgres
      dockerfile: Dockerfile
      shm_size: '1gb'
    container_name: postgres
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    expose:
      - "5432"
    environment:
      POSTGRES_DB: db_django
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root

  redis:
    restart: always
    image: redis
    container_name: redis
    privileged: true
    expose:
      - "6379"

  python:
    restart: always
    build: ./python/
    container_name: python
    privileged: true
    env_file:
      - ./python/python.env
    environment:
      WEB_DOMAIN: 127.0.0.1
    expose:
      - "80"
    links:
      - redis:redis
      - postgres:postgres
    volumes:
      - ./python/data:/www
    command: python manage.py runserver 0.0.0.0:80
    logging:
      driver: "json-file"
      options:
        max-size: "1M"

  nginx:
    restart: always
    build: ./nginx/
    container_name: nginx
    image: nginx
    privileged: true
    logging:
      driver: "json-file"
      options:
        max-size: "1M"
    env_file:
      - ./nginx/nginx.env
    environment:
      NGINX_PORT: 80
      NGINX_HOST: 127.0.0.1
      NGINX_ROOT: /usr/share/nginx/html
      NGINX_API_PORT: 80
      NGINX_API_HOST: 127.0.0.1
      NGINX_API_ROOT: /usr/share/nginx/assets
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/data:/usr/share/nginx/html
      - ./nginx/mysite.template:/etc/nginx/conf.d/mysite.template
      - ./python/data/static:/usr/share/nginx/assets/static
      - ./python/data/uploads:/usr/share/nginx/assets/uploads
      - ./python/data/media:/usr/share/nginx/assets/media
    links:
      - python:python
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

